language: cpp
compiler: gcc
install:
- export CXX="g++-5" CC="gcc-5"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
script: make
os:
- linux
branches:
  only:
  - master
env:
  global:
  - LANG="es_VEN.UTF-8"
