language: cpp
compiler: gcc
# before_install:
# - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
# - sudo apt-get update -qq
install: true
# - sudo apt-get install -qq g++-4.8
# - export CXX="g++-4.8"
script: make
os:
- linux
- osx
branches:
  only:
  - master
env:
  global:
  - LANG="es_VEN.UTF-8"

