#!/bin/bash

# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#########################################################
########                                         ########
# ipdc: Intermedio entre PseudoD y la consola           #
########                                         ########
# Copyright 2016 Alejandro Linarez Rangel
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#########################################################
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Las variables de entorno para PseudoD son:
#
# * `PSEUDODPATH` (pdhelpextracter): Igual que RUTA_PSEUDOD
# * `RUTA_PSEUDOD`: Ruta a la BEPD
# * `RUTA_PSEUDOD_LIB`: Ruta al NEA (libpseudod.so)
# * `RUTA_PSEUDOD_INSTALACION`: Ruta donde se instaló PseudoD
# * `RUTA_PSEUDOD_DEV_LIB`: Ruta a las librerias de desarrollo (si hay)
# * `RUTA_PSEUDOD_BIN`: Ruta al binario de PseudoD (PseudoD)
#
# Los archivos donde podemos escribir estas variales son:
#
# * `$HOME/.bash_profile` (user-only)
# * `$HOME/.profile` (user-only)
# * `/etc/profile`

# Existe la variable RUTA_PSEUDOD?
if [ -z ${RUTA_PSEUDOD+x} ]; then
	# No existe, pero existe el directorio $HOME/.pseudod/bepd/?
	if [ -d "$HOME/.pseudod/bepd/" ]; then
		# Si existe, usa la instalación local
		export RUTA_PSEUDOD="$HOME/.pseudod/bepd/"
	else
		# No existe, usa la instalación global
		export RUTA_PSEUDOD="/opt/pseudod/bepd/"
	fi
fi

# Existe la variable RUTA_PSEUDOD_BIN?
if [ -z ${RUTA_PSEUDOD_BIN+x} ]; then
	# No existe, pero existe el directorio $HOME/.pseudod/bin/?
	if [ -d "$HOME/.pseudod/bin/" ]; then
		# Si existe, usa la instalación local
		export RUTA_PSEUDOD_BIN="$HOME/.pseudod/bin/"
	else
		# No existe, usa la instalación global
		export RUTA_PSEUDOD_BIN="/opt/pseudod/bin/"
	fi
fi

# Existe la variable RUTA_PSEUDOD_LIB?
if [ -z ${RUTA_PSEUDOD_LIB+x} ]; then
	# No existe, pero existe el archivo $HOME/.pseudod/lib/libpseudod.so?
	if [ -e "$HOME/.pseudod/lib/libpseudod.so" ]; then
		# Si existe, usa la instalación local
		export RUTA_PSEUDOD_LIB="$HOME/.pseudod/lib/libpseudod.so"
	else
		# No existe, usa la instalación global
		export RUTA_PSEUDOD_LIB="/opt/pseudod/lib/libpseudod.so"
	fi
fi

# Existe la variable RUTA_PSEUDOD_INSTALACION
if [ -z ${RUTA_PSEUDOD_INSTALACION+x} ]; then
	# No existe, pero existe el directorio $HOME/.pseudod/?
	if [ -d "$HOME/.pseudod/" ]; then
		# Si existe, usa la instalación local
		export RUTA_PSEUDOD_INSTALACION="$HOME/.pseudod/"
	else
		# No existe, usa la instalación global
		export RUTA_PSEUDOD_INSTALACION="/opt/pseudod/"
	fi
fi

param1=$1
param2=$2
param3=$3
param4=$4

function ayuda() {
	echo "Ayuda del Intermedio entre PseudoD y la Consola"
	echo "-----------------------------------------------"
	echo "	$0 -d :Muestra la ruta predeterminada de bepd"
	echo "	$0 -s (ruta) :Fija la ruta de bepd a (ruta)"
	echo "	$0 -f (archivo) :Ejecuta archivo con PseudoD"
	echo "	$0 -i :Inicia el interactivo de PseudoD"
	echo "Combinaciones:---------------------------------"
	echo "	$0 -s (ruta) (opciones) (parametros)"
	echo "	$0 (opciones) -s (ruta) (parametros)"
	echo "	$0 (opciones) (parametros) -s (ruta)"
	echo "Donde:-----------------------------------------"
	echo "	(opciones) -> (-i|-f)"
	echo "	(parametros) -> parametros de la opcion seleccionada"
	echo "	(ruta) -> Ruta de bepd"
	echo "La opcion -s no es obligatorio"
	exit
}

if [ "$param1" = "--help" ]; then
	ayuda
fi
if [ "$param1" = "-h" ]; then
	ayuda
fi
if [ "$param1" = "--ayuda" ]; then
	ayuda
fi

if [ "$param1" = "-d" ]; then
	echo "Ruta a la BEPD predeterminada:"
	echo "$RUTA_PSEUDOD"
	echo "Ruta al NEA predeterminada:"
	echo "$RUTA_PSEUDOD_LIB"
	echo "Ruta a la instalación predeterminada:"
	echo "$RUTA_PSEUDOD_INSTALACION"
	echo "Ruta a las librerias de desarrollo (si hay):"
	echo "$RUTA_PSEUDOD_DEV_LIB"
	exit
fi

if [ "$param1" = "-s" ]; then
	RUTA_PSEUDOD=$param2
	param1=$param3
	param2=$param4
fi

if [ "$param2" = "-s" ]; then
	RUTA_PSEUDOD=$param3
	param2=$param4
fi

if [ "$param3" = "-s" ]; then
	RUTA_PSEUDOD=$param4
fi

if [ "$param1" = "-f" ]; then
	$RUTA_PSEUDOD_BIN/PseudoD "$param2" "$RUTA_PSEUDOD" "$RUTA_PSEUDOD_LIB";
fi

if [ "$param1" = "-i" ]; then
	$RUTA_PSEUDOD_BIN/PseudoD -i "$RUTA_PSEUDOD" "$RUTA_PSEUDOD_LIB";
fi
